<?php
namespace Scry\Volk;
use Composer\Composer;
use Scry;

include_once "target.php";

class Volk
{
    private function Volkname(string|null $class) : string
    {
        return substr(sha1(microtime().$class??"unknown"), 0, 8);
    }

    public function Save(array $content, Scry\Volk\Target $target, ?string $class = null, bool $deleteOthers = true): void
    {
        $date = date('Y-m-d_H-i-s');
        $exportFilename = $this->Volkname($class);
        $export =
        "
<?php\n
// File auto-generated by Scry.
// DO NOT MOVE ANYTHING.
\$var_{$exportFilename}_date = '$date';


return " . var_export($content, true) . ";";

        $storage = $this->GetStorage() . $target->value . DIRECTORY_SEPARATOR;
        $location = $storage . $exportFilename . '.php';

        
        // Ensure the target directory exists, if not create it
        $targetDir = dirname($location);
        
        if (!is_dir($targetDir))
        {
            mkdir($targetDir, 0777, true);
        }

        $map = $this->RequireMap();

        // Delete old $map entries for the same target
        if ($deleteOthers)
        {
            if ($class !== null && isset($map[$target->value][$class]) && file_exists($map[$target->value][$class]))
            {
                unlink($map[$target->value][$class]);
            }
            elseif (isset($map[$target->value]) && file_exists($map[$target->value]))
            {
                unlink($map[$target->value]);
            }
        }
        
        // Create new file
        file_put_contents($location, $export);

        // Update map
        if ($class !== null)
        {
            $map[$target->value][$class] = $location;
        }
        else
        {
            $map[$target->value] = $location;
        }

        $this->SaveMap($map);
    }



    public function RequireDump(Scry\Volk\Target $target, ?string $class = null) : array|null
    {
        $map = $this->RequireMap();
        if ($class !== null && isset($map[$target->value][$class]) && file_exists($map[$target->value][$class]))
        {
            return require $map[$target->value][$class];
        }
        elseif (isset($map[$target->value]) && file_exists($map[$target->value]))
        {
            return require $map[$target->value];
        }

        return null;
    }

    public function RequireMap() : array
    {
        if(!file_exists($this->MapFileLocation()))
        {
            return [
                Scry\Volk\Target::AttributeFiles->value => '',
                Scry\Volk\Target::SpecificClassFile->value => []
            ];
        }

        return require $this->MapFileLocation();
    }

    private function SaveMap(array $map) : void
    {
        $date = date('d/m/Y H:i:s');
        $content = "<?php\n// Map updated on $date\n\nreturn " . var_export($map, true) . ";\n";
        file_put_contents($this->MapFileLocation(), $content);
    }

    public function MapFileLocation() : string
    {
        return $this->GetStorage() . 'map.php';
    }

    /**
    *
  ________        __    __                       
 /  _____/  _____/  |__/  |_  ___________  ______
/   \  ____/ __ \   __\   __\/ __ \_  __ \/  ___/
\    \_\  \  ___/|  |  |  | \  ___/|  | \/\___ \ 
 \______  /\___  >__|  |__|  \___  >__|  /____  >
        \/     \/                \/           \/ 
     */

    public function GetStorage() : string
    {
        return \Composer\Composer::CorrectPath(__DIR__ . '/volks/');
    }
}
